# Generated by shellforge. Do not edit — regenerate instead.
#
# Source this from your ~/.bashrc, as the LAST line:
#
#   [ -f "$HOME/.config/shellforge/init.bash" ] && . "$HOME/.config/shellforge/init.bash"
#
# Blocks below are emitted in dependency order (path -> tool -> prompt ->
# last). Reordering them by hand will break hooks that require a specific
# position, which is the problem shellforge exists to solve.

# --- bat (tool) ---
if command -v bat >/dev/null 2>&1; then
  export BAT_THEME="ansi"
  alias cat='bat --paging=never'
fi

# --- eza (tool) ---
if command -v eza >/dev/null 2>&1; then
  alias ls='eza --group-directories-first'
  alias ll='eza -l --group-directories-first --git'
  alias tree='eza --tree'
fi

# --- fzf (tool) ---
if command -v fzf >/dev/null 2>&1; then
  eval "$(fzf --bash)"
fi

# --- starship (prompt) ---
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init bash)"
fi

# --- zoxide (last) ---
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init bash)"
fi

