# Generated by shellforge. Do not edit — regenerate instead.
#
# Source this from your ~/.zshrc, as the LAST line:
#
#   [ -f "$HOME/.config/shellforge/init.zsh" ] && . "$HOME/.config/shellforge/init.zsh"
#
# Blocks below are emitted in dependency order (path -> tool -> prompt ->
# last). Reordering them by hand will break hooks that require a specific
# position, which is the problem shellforge exists to solve.

# --- mise (path) ---
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

